apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'spring-boot-app'
        static_configs:
          - targets: ['spring-boot-app-service.default.svc.cluster.local:8089']
        metrics_path: '/SpringMVC/actuator/prometheus'
      
