apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up-job
spec:
  schedule: "0 0 22-28 11 3"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scale-up
              image: bitnami/kubectl:latest
              command:
                - "/bin/sh"
                - "-c"
                - "kubectl scale --replicas=10 deployment/spring-boot-app"
          restartPolicy: OnFailure