apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-job
spec:
  schedule: "0 0 23-31 11 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scale-down
              image: bitnami/kubectl:latest
              command:
                - "/bin/sh"
                - "-c"
                - "kubectl scale --replicas=3 deployment/spring-boot-app"
          restartPolicy: OnFailure
