apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: mortadhagaied/projetdevops:${env.VERSION}
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{
            "server.servlet.context-path": "/SpringMVC",
            "server.port": "8089",
            "spring.datasource.url": "jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
            "spring.datasource.username": "root",
            "spring.datasource.password": "password",
            "spring.jpa.show-sql": "true",
            "spring.jpa.hibernate.ddl-auto": "update",
            "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
          }'
