apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - name: http
      protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer
